[package]
name = "ratatui_router"
version = "0.1.0"
edition = "2024"


[dependencies]
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.29.0"
ratatui_router_derive = { path = "ratatui_router_derive" }
color-eyre = "0.6.5"


